# The URL the site will be built for
base_url = "https://lymslive.github.io"

title = "沉思涧"

# zh 中文不支持搜索，故仍设 en
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# https://www.getzola.org/themes/deepthought/
theme = "DeepThought"

taxonomies = [
    { name = "categories", feed = true, paginate_by = 50 },
    { name = "tags", feed = true, paginate_by = 50 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "首页" },
        { url = "$BASE_URL/blog", name = "博客" },
        { url = "$BASE_URL/book", name = "书册" },
        { url = "$BASE_URL/think", name = "文思" },
        { url = "$BASE_URL/white", name = "白学" },
        { url = "$BASE_URL/tags", name = "标签" },
        { url = "$BASE_URL/categories", name = "归类" },
#       { url = "$BASE_URL/resume", name = "简历" },
    ] },
]

[extra.author]
# name = "lymslive"
name = "七阶子"
avatar = "images/avatar.png"

[extra.social]
github = "lymslive"
email = "403708621@qq.com"

